name: Build docker image

on:
  push:
    branches:
      - main
      - update-dockerfile-no-wh

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up buildx
        uses: docker/setup-buildx-action@v2
      - name: construct image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/praekeltfoundation/flow-results
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix={{branch}}-,enable=${{ github.ref_type != 'tag' }}
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
