name: Build docker image

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          postgres_version: ['12', '13', '14']
      services:
        postgres:
          image: postgres:${{ matrix.postgres_version }}
          env:
            POSTGRES_DB: flow_results
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          ports:
            - 5432:5432
      env:
        FLOW_RESULTS_DATABASE: postgres://postgres:postgres@localhost:5432/flow_results
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up buildx
        uses: docker/setup-buildx-action@v2
      - name: construct image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/praekeltfoundation/flow-results
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix={{branch}}-,enable=${{ github.ref_type != 'tag' }}
      - name: login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
